---
- name: Install & Setup kops
  hosts: kopssrvgrp
  gather_facts: no
  tasks:
    - name: Download & configure kops
      get_url:
        url: "https://github.com/kubernetes/kops/releases/download/v1.26.4/kops-linux-amd64"
        dest: /usr/local/bin/kops
        owner: ubuntu
        group: ubuntu
        mode: 0755
        force: yes
      become: true